# Generated by Django 4.1.7 on 2023-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
            ],
        ),
    ]
